# Generated by Django 5.2.1 on 2025-06-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigi_cam', '0002_alter_persona_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chat ID de Telegram'),
        ),
    ]
