# Generated by Django 5.2.1 on 2025-06-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigi_cam', '0003_cliente_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('usuario', 'Usuario'), ('usuario_con_beneficios', 'Usuario con beneficios')], default='usuario', max_length=22, verbose_name='Rol del usuario'),
        ),
    ]
